### ISSUE TITLE
Site Email im Backoffice wird obfuscated 

### ISSUE THREAD

**Issue by jb-simon** [joinbox/drupal-module-email-obfuscator#2]
Backoffice:
![Screenshot 2023-03-27 at 10 47 19](https://user-images.githubusercontent.com/114908607/227892268-960ca691-1751-4a62-81b0-4aac8fd3d12c.png)

Placeholder im Frontend:
![Screenshot 2023-03-29 at 15 37 41](https://user-images.githubusercontent.com/114908607/228556151-36a8aa4e-ec8f-4d09-896f-899ecb7cb75f.png)

**Comment by hudsonmuff** [comment]
Input placeholders in forms are also fixed now.

For D9 use version `1.1.0`
For D10 use version `2.1.0`
