### ISSUE TITLE
Emails in Form-Inputs sollten nicht obfuscated werden

### ISSUE THREAD

**Issue by jb-simon** [joinbox/drupal-module-email-obfuscator#5]
![Screenshot 2023-10-09 at 10 04 15](https://github.com/joinbox/drupal-module-email-obfuscator/assets/114908607/4e6aa2bd-a272-4560-81fe-c63e86d686bc)

**Schritte zum reproduzieren:**
1. Formular ausfüllen & Error provozieren (z.B. Pflichtfeld auslassen)
2. Beim Neuladen des Formulars ist die Email obfuscated

**Mögliche Lösung:**

`!str_contains($request->getRequestUri(), 'ajax_form=1')`
Als weitere Condition, wann Obfuscated werden soll.

**Comment by fxstr** [comment]
Vermutlich würde es reichen, die [Attribute wie besprochen auszunehmen](https://github.com/joinbox/drupal-module-email-obfuscator/issues/4#event-10552090705): Die Mail kommt hier in einem `value`-Attribut daher.

**Comment by hudsonmuff** [comment]
@fxstr finde ich gut. Dann setze ich das so schnell wie möglich um.

**Comment by hudsonmuff** [comment]
Fixed with #12 (v2.2.0 & v1.2.0)
