### ISSUE TITLE
Email addresses in hrefs containing a trailing space are dual-obfuscated

### ISSUE THREAD

**Issue by fxstr** [joinbox/drupal-module-email-obfuscator#7]
See https://github.com/joinbox/edulog/issues/280: If the href attribute contains a space (before the closing quote), the email address is dual-obfuscated (reverted **and** span injected). 

Bug might be fixed with https://github.com/joinbox/drupal-module-email-obfuscator/pull/6 but we need test cases to make sure it actually does.

**Comment by hudsonmuff** [comment]
Fixed with #12 (v2.2.0 / v1.2.0)
