### ISSUE TITLE
Clicking an email in a link switches obfuscation on and off

### ISSUE THREAD

**Issue by fxstr** [joinbox/drupal-module-email-obfuscator#8]
Every click on an email address changes its obfuscation state (in the `href` attribute): from reversed to non-reversed to reversed. We must make sure that `onclick`, we only de-obfuscate **once**. Solution is not clear at the moment (because `onclick` handlers only accept JS expressions, not full featured instructions).

**Comment by fxstr** [comment]
Maybe: `!this.dataset.obfuscated && this.dataset.obfuscated = true && this.setAttribute('href', a.getAttribute('href').split('').reverse().join(''))`

**Comment by fxstr** [comment]
Maybe: Also add `onmouseover`

**Comment by hudsonmuff** [comment]
Fixed with https://github.com/joinbox/drupal-module-email-obfuscator/pull/12 (v2.2.0 & v1.2.0)
